# API Contract: Task Management Endpoints
# Feature: 001-backend-auth-tasks
# Date: 2025-12-18

openapi: 3.0.3
info:
  title: Task Management API
  description: Auth-protected task management with user isolation
  version: 1.0.0
  contact:
    name: Backend Team
    email: backend@example.com

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.example.com
    description: Production server

security:
  - BearerAuth: []

tags:
  - name: tasks
    description: Task management operations

paths:
  /api/{user_id}/tasks:
    get:
      summary: List all tasks for authenticated user
      tags: [tasks]
      operationId: getTasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT token)
          schema:
            type: string
            example: "user-123"
      responses:
        '200':
          description: Successfully retrieved tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

    post:
      summary: Create a new task
      tags: [tasks]
      operationId: createTask
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT token)
          schema:
            type: string
            example: "user-123"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '422':
          $ref: '#/components/responses/ValidationError'

  /api/{user_id}/tasks/{id}:
    get:
      summary: Get a single task by ID
      tags: [tasks]
      operationId: getTask
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT token)
          schema:
            type: string
            example: "user-123"
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Successfully retrieved task
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update a task (full replacement)
      tags: [tasks]
      operationId: updateTask
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT token)
          schema:
            type: string
            example: "user-123"
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'

    patch:
      summary: Partially update a task (e.g., toggle completion status)
      tags: [tasks]
      operationId: patchTask
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT token)
          schema:
            type: string
            example: "user-123"
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskPatch'
      responses:
        '200':
          description: Task patched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'

    delete:
      summary: Delete a task
      tags: [tasks]
      operationId: deleteTask
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT token)
          schema:
            type: string
            example: "user-123"
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Task deleted successfully (no content)
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from Better Auth

  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Task ID (auto-increment)
          example: 1
        user_id:
          type: string
          description: User ID from JWT token
          example: "user-123"
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: Optional task description
          example: "Milk, eggs, and bread"
        completed:
          type: boolean
          description: Task completion status
          example: false
        created_at:
          type: string
          format: date-time
          description: Timestamp when task was created
          example: "2025-12-18T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp when task was last updated
          example: "2025-12-18T10:35:00Z"

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: Optional task description
          example: "Milk, eggs, and bread"

    TaskUpdate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title
          example: "Buy groceries (updated)"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: Optional task description
          example: "Milk, eggs, bread, and butter"

    TaskPatch:
      type: object
      required:
        - completed
      properties:
        completed:
          type: boolean
          description: Task completion status
          example: true

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Invalid or expired token"

  responses:
    BadRequest:
      description: Bad request (validation error, malformed JSON)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Invalid input data"

    Unauthorized:
      description: Unauthorized (missing, invalid, or expired JWT token)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Invalid or expired token"

    Forbidden:
      description: Forbidden (user_id in path does not match JWT token)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "User ID mismatch"

    NotFound:
      description: Not Found (task doesn't exist or doesn't belong to user)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Task not found"

    ValidationError:
      description: Unprocessable Entity (Pydantic validation error)
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: array
                items:
                  type: object
                  properties:
                    loc:
                      type: array
                      items:
                        type: string
                    msg:
                      type: string
                    type:
                      type: string
          example:
            detail:
              - loc: ["body", "title"]
                msg: "field required"
                type: "value_error.missing"
