/**
 * Task entity types
 * Represents a to-do item owned by a specific user
 */
export interface Task {
  id: string;                  // UUID generated by backend
  user_id: string;             // Foreign key to User (enforces data isolation)
  title: string;               // Short description (max 200 chars)
  description: string | null;  // Optional detailed info (max 2000 chars)
  completed: boolean;          // Task completion status
  due_date: string | null;    // Optional due date (ISO 8601 timestamp)
  due_date_end: string | null; // Optional due date end (for date range)
  priority: 'low' | 'medium' | 'high' | null;  // Optional priority level
  category: string | null;     // Optional category/tag
  created_at: string;          // ISO 8601 timestamp
  updated_at: string;          // ISO 8601 timestamp
}

/**
 * Input type for creating a new task
 */
export interface CreateTaskInput {
  title: string;
  description?: string;
  due_date?: string | null;
  due_date_end?: string | null;
  priority?: 'low' | 'medium' | 'high' | null;
  category?: string | null;
}

/**
 * Input type for updating an existing task (partial update)
 */
export interface UpdateTaskInput {
  title?: string;
  description?: string | null;
  completed?: boolean;
  due_date?: string | null;
  due_date_end?: string | null;
  priority?: 'low' | 'medium' | 'high' | null;
  category?: string | null;
}
